# https://jekyll.github.io/jekyll-seo-tag/usage/
title: Datensicherungsstrategien - Physikalische Aufbewahrung
description: Konzepte f√ºr Privatnutzer zur sicheren Aufbewahrung ihrer Daten
lang: de_DE
url: https://sicherungsstrategien.de
google_analytics:

# https://help.github.com/articles/adding-a-jekyll-theme-to-your-github-pages-site/
theme: jekyll-theme-slate

# https://jekyllrb.com/docs/variables/
show_downloads: false

# https://help.github.com/articles/repository-metadata-on-github-pages/#available-repository-metadata
